Puts trusty repository back in
Default image (12) from travis-CI doesn't support VM. Trying trusty
ValueError: Host does not support any virtualization options